title: YANG Yaxiong lab's Homepage
page-top-title: YANG Yaxiong Laboratory
top-section-bg-text: Research on Calcium Channels, Caclium Signaling, and Related Diseases
home-subtitle: YANG Yaxiong Lab&ensp;|&ensp;杨亚雄实验组
copyright-text: '&copy; YANG Yaxiong Lab 2023-2025. All Rights Reserved.'
